### PR TITLE
Update the Open Liberty devifle to version 0.4.3

### PR DESCRIPTION
**Pull request by mezarin**
FYI @ajm01, @scottkurz, @elsony

### CODE REVIEW

**Review by ajm01 — APPROVED** [review]
LGTM

**Review by ajm01 — APPROVED** [review]

**Comment by scottkurz** [comment]
@ajm01 @mezarin we should be submitting the PRs to the new devfile registry repo:    https://github.com/devfile/registry

**Review by elsony — CHANGES_REQUESTED** [review]
See my comment on https://github.com/devfile/registry/pull/15#pullrequestreview-632775252 and resolve the start project problem first.

**Review by elsony — APPROVED** [review]
/lgtm (see https://github.com/devfile/registry/pull/15#issuecomment-818684653 for details)

**Pull request merged**
