### PR TITLE
Add python and python-django devfiles

### PR DESCRIPTION
**Pull request by kadel**
https://github.com/openshift/odo/issues/2327

### CODE REVIEW

**Comment by gorkem** [comment]
How about debug ? Something like [this](https://github.com/gorkem/odo-devfile/blob/0b6ac5b21bf96e00890d1268fa1b25826e2ff026/python-example/devfile.yaml#L28) perhaps?

**Comment by kadel** [comment]
> How about debug ? Something like [this](https://github.com/gorkem/odo-devfile/blob/0b6ac5b21bf96e00890d1268fa1b25826e2ff026/python-example/devfile.yaml#L28) perhaps?

oh, forgot about that :-(
I'll add it

**Comment by dgolovin** [comment]
@kadel  Does not work for me until I replace ${POJECT_SOURCE} with `/projects`. After this change I can push and run `odo debug port-forward` and connect to pushed component manually creating local launch configuration for vscode project.

s2i python component does not provide debugging at all, I can run 'odo push --debug' and 'odo debug port-forward' but connection to debug port is still refused.

**Comment by kadel** [comment]
> @kadel Does not work for me until I replace ${POJECT_SOURCE} with `/projects`. After this change I can push and run `odo debug port-forward` and connect to pushed component manually creating local launch configuration for vscode project.

Ah, good catch.`PROJECT_SOURCE` env variable was added after we cut 2.0.0 release :-( So this wouldn't work with 2.0.0 odo :-(

**Pull request merged**
