### PR TITLE
Offer the Vert.x Openshift examples as starters

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by elsony** [comment]
Changes look ok but it looks like some vertx test cases are failing even after rerunning the build, e.g.
```
cat: out.txt+jdb -attach 5858
: No such file or directory
+[ 1 -ne 0 ]
+echo debugger not working
debugger not working
+sleep 10
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
```

**Comment by jponge** [comment]
This may be unrelated, e.g. some projects may use a DB.

**Comment by elsony** [comment]
I have tried to rebuild a couple of times but the tests failed consistently (and other PR builds went ok). Therefore, it looks like the error does cause by the new changes. We'll need to fix that and make sure the tests run ok before I can merge.

**Comment by jponge** [comment]
Would you have more details on which tests failed and how?

**Comment by elsony** [comment]
Here is the test script: https://github.com/odo-devfiles/registry/tree/master/scripts

It looks like it is failing on the debug tests for vertx. Details on test results can be found here: https://github.com/odo-devfiles/registry/pull/62/checks?check_run_id=1463138938 (just search for "fail")

**Comment by jponge** [comment]
@elsony Sorry for not getting back to you earlier but I have found the problem.

The problem is that the test script (`scripts/test.sh`) uses `curl -I`, which emits a HTTP HEAD request. It turns out that Vert.x has a strict HTTP routing, so it's not because you can respond on `GET` that `HEAD` is implicitly available.

By replacing `curl -I` with `curl -i` (which is more verbose with the body payload) then it passes.

**Comment by jponge** [comment]
Also see #73

**Comment by jponge** [comment]
With #73 on top of this branch:

```
(...)

+ echo 'FAILURE: FAILED TESTS:  java-wildfly java-wildfly-bootable-jar'
FAILURE: FAILED TESTS:  java-wildfly java-wildfly-bootable-jar
+ exit 1
```

**Review by elsony — APPROVED** [review]
/lgtm

**Pull request merged**
