### PR TITLE
[WIP] Setting up test scripts

### PR DESCRIPTION
**Pull request by amitkrout**
Aiding test scripts to test devefile registry components

Parent issue - https://github.com/openshift/odo/issues/3378

### CODE REVIEW

**Review by mohammedzee1000 — COMMENTED** [review]
What about example app?

**Comment by amitkrout** [comment]
Ping @kadel 

Feel free to close this pr once your test scripts pr is ready

**Comment by amitkrout** [comment]
```
+odo create java-maven --devfile java-maven/devfile.yaml --context /tmp/tmp.Ks9HmEmfbG
Experimental mode is enabled, use at your own risk
Validation
 ✓  Creating a devfile component from devfile path: /home/travis/gopath/src/github.com/odo-devfiles/registry/devfiles/java-maven/devfile.yaml [407172ns]
 ✓  Validating devfile component [220704ns]
Please use `odo push` command to create the component with source deployed
+odo push --context /tmp/tmp.Ks9HmEmfbG
Validation
 ✓  Validating the devfile [438246ns]
Creating Kubernetes resources for component java-maven
 ✓  Waiting for component to start [39s]
Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.
Syncing to component java-maven
 ✓  Checking files for pushing [357266ns]
 ✓  Syncing files to the component [136ms]
Executing devfile commands for component java-maven
 ◑  Executing mvn-package command "mvn package" ✗  
Unable to exec command [/bin/sh -c mvn package]: 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.195 s
[INFO] Finished at: 2020-08-17T16:32:09Z
[INFO] ------------------------------------------------------------------------


[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/projects). Please verify you invoked Maven from the correct directory. -> [Help 1]


[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
 ✗  Executing mvn-package command "mvn package" [2s]
 ✗  Failed to start component with name java-maven. Error: Failed to create the component: unable to execute the build command: error while streaming command: command terminated with exit code 1
The command "./scripts/e2e-tests.sh" exited with 1.
```
Ping @dev-gaur

**Comment by kadel** [comment]
@amitkrout based on the error it looks like you are executing odo push in a wrong directory

**Comment by amitkrout** [comment]
> @amitkrout based on the error it looks like you are executing odo push in a wrong directory

@kadel I am able to reproduce it locally too. 
```
$ pwd
/Users/amit/go/src/github.com/odo-devfiles/registry/devfiles/java-maven

$ odo component create java-maven --devfile ./devfile.yaml --project test1234
Experimental mode is enabled, use at your own risk

Validation
 ✓  Creating a devfile component from devfile path: /Users/amit/go/src/github.com/odo-devfiles/registry/devfiles/java-maven/devfile.yaml [376641ns]
 ✓  Validating devfile component [151357ns]

Please use `odo push` command to create the component with source deployed


$ odo push

Validation
 ✓  Validating the devfile [87657ns]

Creating Kubernetes resources for component java-maven
 ✓  Waiting for component to start [55s]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component java-maven
 ✓  Checking files for pushing [554832ns]
 ✓  Syncing files to the component [2s]

Executing devfile commands for component java-maven
 ◒  Executing mvn-package command "mvn package", if not running ✗  
Unable to exec command [/bin/sh -c mvn package]: 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.133 s
[INFO] Finished at: 2020-08-18T08:40:52Z
[INFO] ------------------------------------------------------------------------




[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/projects). 
Please verify you invoked Maven from the correct directory. -> [Help 1]




[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

 ✗  Executing mvn-package command "mvn package", if not running [5s]
 ✗  Failed to start component with name java-maven. Error: Failed to create the component: command execution failed: unable to execute the run command: error while streaming command: command terminated with exit code 1
```
POM.xml is missing for maven dependencies download. So may be the sample project source is missing in the devfile causing the problem. However similar failure i can see for component ```java-openliberty``` and ```java-quarkus```. 

Component ```nodejs``` and ```java-springboot``` devfile works fine.

**Comment by kadel** [comment]
you are creating components in `/Users/amit/go/src/github.com/odo-devfiles/registry/devfiles/java-maven` I assume that this path doesn't contain project source but only devfile.yaml. So it is expected that it is failing.

**Comment by amitkrout** [comment]
> you are creating components in `/Users/amit/go/src/github.com/odo-devfiles/registry/devfiles/java-maven` I assume that this path doesn't contain project source but only devfile.yaml. So it is expected that it is failing.

Yes, so i am expecting project field here in the devfile only for our testing and the sample project should be available in https://github.com/odo-devfiles/registry/ repo.  For example https://github.com/odo-devfiles/registry/blob/master/devfiles/java-springboot/devfile.yaml#L5-L8

**Comment by kadel** [comment]
This is not how it currently works. You have to clone the project manually.

**Comment by kadel** [comment]
@amitkrout https://github.com/odo-devfiles/registry/pull/34

**Comment by amitkrout** [comment]
Ping @anandrkskd 
/close

**Pull request closed without merging**
