### PR TITLE
Vert.x devfile

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by kadel** [comment]
Failing tests are ok. It is just complaining that there are more devfiles that test run. I'll address this later.

**Comment by kadel** [comment]
If I try to push updates to a running application I get the following error:
```
▶ odo push

Validation
 ✓  Validating the devfile [57604ns]

Creating Kubernetes resources for component java-vertx
 ✓  Waiting for component to start [140ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component java-vertx
 ✓  Checking file changes for pushing [5ms]
 ✓  Syncing files to the component [3s]

Executing devfile commands for component java-vertx
 ✗  Executing mvn-package command "mvn package" [6s]
 ✗  Failed to start component with name java-vertx. Error: Failed to create the component: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c mvn package]:
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.example:starter >-------------------------
[INFO] Building starter 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /projects/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ starter ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ starter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /projects/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ starter ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ starter ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.starter.TestMainVerticle
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.423 s <<< FAILURE! - in com.example.starter.TestMainVerticle
[ERROR] verticle_deployed{Vertx, VertxTestContext}  Time elapsed: 0.419 s  <<< ERROR!
java.net.BindException: Address already in use

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestMainVerticle.verticle_deployed » Bind Address already in use
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.525 s
[INFO] Finished at: 2020-10-22T14:33:19Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project starter: There are test failures.
[ERROR]
[ERROR] Please refer to /projects/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
: error while streaming command: command terminated with exit code 1

```

I don't know much about Java or Vert.x but is it possible that the tests are trying to run the application on the same port as where the "real" application is running?

**Comment by jponge** [comment]
Ah yes indeed, the test opens the same port.

**Comment by jponge** [comment]
Also note that https://github.com/jponge/vertx-ex would need to be moved to the organisation that holds the other templates (Quarkus, Spring, etc).

**Comment by jponge** [comment]
@kadel I can look at using a random port for testing.

**Comment by jponge** [comment]
Does the same problem appear with other stacks? I guess it should unless ports are made dynamic.

**Comment by jponge** [comment]
> @kadel I can look at using a random port for testing.

Ok so in theory I could do that, but it's not elegant.

**Comment by jponge** [comment]
@kadel ok I did the same thing as the Spring devfile and disabled tests on build

**Comment by mik-dass** [comment]
The devfile works for me. I was able to push, hit the URL, attach a debugger etc :+1: 
Please add a vertx test to the test.sh script file https://github.com/odo-devfiles/registry/blob/b6f0435a445f3b271f33b477cb2a88ac1f2211cc/scripts/test.sh#L148
 to clear the CI.

**Comment by kadel** [comment]
> The devfile works for me. I was able to push, hit the URL, attach a debugger etc 👍
> Please add a vertx test to the test.sh script file

I will do that in a separate PR. The testing script is in bad shape, I will have to clean it up anyway

**Comment by jponge** [comment]
Thanks, please ping me if you need help.

**Comment by jponge** [comment]
BTW the template project should be moved over to https://github.com/odo-devfiles/vertx-ex

**Pull request merged**
