### PR TITLE
Update quarkus devfile with starter project

### PR DESCRIPTION
**Pull request by adisky**
Add Starter project for quarkus devfile
https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started

### CODE REVIEW

**Review by elsony — COMMENTED** [review]
The changes on the devfile looks good. For the sample app itself, I'd suggest to focus on showcase the java code execution given that it is a java stack.  The existing index.html page is just a pure html page and it looks more like an information page only with no java code execution. If I just use `--downloadSource` to clone this sample on odo, I ended up have to inspect the source before I know I can call the /hello URL to execute java code.  Therefore, I'd suggest to add a link to the index.html that brings the user to the /hello URL to execute some java code.

**Comment by adisky** [comment]
> The changes on the devfile looks good. For the sample app itself, I'd suggest to focus on showcase the java code execution given that it is a java stack. The existing index.html page is just a pure html page and it looks more like an information page only with no java code execution. If I just use `--downloadSource` to clone this sample on odo, I ended up have to inspect the source before I know I can call the /hello URL to execute java code. Therefore, I'd suggest to add a link to the index.html that brings the user to the /hello URL to execute some java code.

@elsony to update the index.html page, either i need to create a PR in quarkus repo or fork the project here.
if you check the readme page of the project it clearly specifies about the `/hello` endpoint. Suggest what to do here, if you want we could maintain a quarkus project fork here.

**Comment by adisky** [comment]
@elsony updated the devfile and forked the project here https://github.com/odo-devfiles/quarkus-ex with requested changes.

**Comment by elsony** [comment]
@adisky I tested it out and it looks good. I can merge it after you rebase to latest.

**Comment by adisky** [comment]
@elsony rebased

**Review by elsony — APPROVED** [review]
LGTM

**Pull request merged**
