### PR TITLE
Fix travis `url list`; update java-openliberty to v0.3.0; fix java-openliberty Travis test

### PR DESCRIPTION
**Pull request by scottkurz**

### CODE REVIEW

**Comment by scottkurz** [comment]
@elsony - I think I fixed the Travis issue.   Thanks.

**Comment by scottkurz** [comment]
Not sure why there are two separate Travis CI checks.. the [second](https://github.com/odo-devfiles/registry/pull/57/checks?check_run_id=1262273281)
passes but the [first](https://github.com/odo-devfiles/registry/pull/57/checks?check_run_id=1262273280)
still shows as "Queued"

**Review by elsony — APPROVED** [review]
LGTM

**Comment by elsony** [comment]
Looks like the build summary is not updated properly. The individual test results are green (https://travis-ci.com/github/odo-devfiles/registry/jobs/400449572 and https://travis-ci.com/github/odo-devfiles/registry/jobs/400449573). So merging.

**Pull request merged**
