### PR TITLE
Update to latest open liberty devfile

### PR DESCRIPTION
**Pull request by awisniew90**
Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>

### CODE REVIEW

**Comment by scottkurz** [comment]
LGTM.  We're trying to start down a path with fine-grained (separately versioned) devfile vs outer loop build artifacts.   Hence the 0.4.1 vs. 0.5.0.   At the least it'd be easier to switch to versioning everything together later than to switch in the other direction.

**Comment by awisniew90** [comment]
Failures are only for java-wildfly-bootable-jar: `FAILURE: FAILED TESTS:  java-wildfly-bootable-jar` - Is this safe to merge?

**Comment by scottkurz** [comment]
@elsony can we please merge this?

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by elsony** [comment]
Changes look good but PR build failed. The failure doesn't look like related to this PR though. I tried to rerun the PR test build but it can't be rerun for some reasons. I'll try the rerun later.

**Comment by awisniew90** [comment]
Hi @elsony  - Since the failures are unrelated to the liberty devfile, can we merge this?

**Comment by elsony** [comment]
Given that the error is unrelated to this change (wildfly failure and open liberty test passed) and I currently cannot kick off a retest, I am merging this aged PR as requested.

**Pull request merged**
